export const keys = {
  Backquote: {
    en: { key: '`', keyUp: '`' },
    ru: { key: 'ё', keyUp: 'Ё' },
    isFunc: false,
    width: '40px',
  },
  Digit1: {
    en: { key: '1', keyUp: '!' },
    ru: { key: '1', keyUp: '!' },
    isFunc: false,
    width: '40px',
  },
  Digit2: {
    en: { key: '2', keyUp: '@' },
    ru: { key: '2', keyUp: '"' },
    isFunc: false,
    width: '40px',
  },
  Digit3: {
    en: { key: '3', keyUp: '#' },
    ru: { key: '3', keyUp: '№' },
    isFunc: false,
    width: '40px',
  },
  Digit4: {
    en: { key: '4', keyUp: '$' },
    ru: { key: '4', keyUp: ';' },
    isFunc: false,
    width: '40px',
  },
  Digit5: {
    en: { key: '5', keyUp: '%' },
    ru: { key: '5', keyUp: '%' },
    isFunc: false,
    width: '40px',
  },
  Digit6: {
    en: { key: '6', keyUp: '^' },
    ru: { key: '6', keyUp: ':' },
    isFunc: false,
    width: '40px',
  },
  Digit7: {
    en: { key: '7', keyUp: '&' },
    ru: { key: '7', keyUp: '?' },
    isFunc: false,
    width: '40px',
  },
  Digit8: {
    en: { key: '8', keyUp: '*' },
    ru: { key: '8', keyUp: '*' },
    isFunc: false,
    width: '40px',
  },
  Digit9: {
    en: { key: '9', keyUp: '(' },
    ru: { key: '9', keyUp: '(' },
    isFunc: false,
    width: '40px',
  },
  Digit0: {
    en: { key: '0', keyUp: ')' },
    ru: { key: '0', keyUp: ')' },
    isFunc: false,
    width: '40px',
  },
  Minus: {
    en: { key: '-', keyUp: '_' },
    ru: { key: '-', keyUp: '_' },
    isFunc: false,
    width: '40px',
  },
  Equal: {
    en: { key: '=', keyUp: '+' },
    ru: { key: '=', keyUp: '+' },
    isFunc: false,
    width: '40px',
  },
  Backspace: {
    en: { key: 'Backspace', keyUp: 'Backspace' },
    ru: { key: 'Backspace', keyUp: 'Backspace' },
    isFunc: true,
    width: '100px',
  },
  Tab: {
    en: { key: 'Tab', keyUp: 'Tab' },
    ru: { key: 'Tab', keyUp: 'Tab' },
    isFunc: true,
    width: '45px',
  },
  KeyQ: {
    en: { key: 'q', keyUp: 'Q' },
    ru: { key: 'й', keyUp: 'Й' },
    isFunc: false,
    width: '40px',
  },
  KeyW: {
    en: { key: 'w', keyUp: 'W' },
    ru: { key: 'ц', keyUp: 'Ц' },
    isFunc: false,
    width: '40px',
  },
  KeyE: {
    en: { key: 'e', keyUp: 'E' },
    ru: { key: 'у', keyUp: 'У' },
    isFunc: false,
    width: '40px',
  },
  KeyR: {
    en: { key: 'r', keyUp: 'R' },
    ru: { key: 'к', keyUp: 'К' },
    isFunc: false,
    width: '40px',
  },
  KeyT: {
    en: { key: 't', keyUp: 'T' },
    ru: { key: 'е', keyUp: 'Е' },
    isFunc: false,
    width: '40px',
  },
  KeyY: {
    en: { key: 'y', keyUp: 'Y' },
    ru: { key: 'н', keyUp: 'Н' },
    isFunc: false,
    width: '40px',
  },
  KeyU: {
    en: { key: 'u', keyUp: 'U' },
    ru: { key: 'г', keyUp: 'Г' },
    isFunc: false,
    width: '40px',
  },
  KeyI: {
    en: { key: 'i', keyUp: 'I' },
    ru: { key: 'ш', keyUp: 'Ш' },
    isFunc: false,
    width: '40px',
  },
  KeyO: {
    en: { key: 'o', keyUp: 'O' },
    ru: { key: 'щ', keyUp: 'Щ' },
    isFunc: false,
    width: '40px',
  },
  KeyP: {
    en: { key: 'p', keyUp: 'P' },
    ru: { key: 'з', keyUp: 'З' },
    isFunc: false,
    width: '40px',
  },
  BracketLeft: {
    en: { key: '[', keyUp: '{' },
    ru: { key: 'х', keyUp: 'Х' },
    isFunc: false,
    width: '40px',
  },
  BracketRight: {
    en: { key: ']', keyUp: '}' },
    ru: { key: 'ъ', keyUp: 'Ъ' },
    isFunc: false,
    width: '40px',
  },
  Backslash: {
    en: { key: '\\', keyUp: '|' },
    ru: { key: '\\', keyUp: '/' },
    isFunc: false,
    width: '40px',
  },
  Delete: {
    en: { key: 'Del', keyUp: 'Del' },
    ru: { key: 'Del', keyUp: 'Del' },
    isFunc: true,
    width: '45px',
  },
  CapsLock: {
    en: { key: 'CapsLock', keyUp: 'CapsLock' },
    ru: { key: 'CapsLock', keyUp: 'CapsLock' },
    isFunc: true,
    width: '90px',
  },
  KeyA: {
    en: { key: 'a', keyUp: 'A' },
    ru: { key: 'ф', keyUp: 'Ф' },
    isFunc: false,
    width: '40px',
  },
  KeyS: {
    en: { key: 's', keyUp: 'S' },
    ru: { key: 'ы', keyUp: 'Ы' },
    isFunc: false,
    width: '40px',
  },
  KeyD: {
    en: { key: 'd', keyUp: 'D' },
    ru: { key: 'в', keyUp: 'В' },
    isFunc: false,
    width: '40px',
  },
  KeyF: {
    en: { key: 'f', keyUp: 'F' },
    ru: { key: 'а', keyUp: 'А' },
    isFunc: false,
    width: '40px',
  },
  KeyG: {
    en: { key: 'g', keyUp: 'G' },
    ru: { key: 'п', keyUp: 'П' },
    isFunc: false,
    width: '40px',
  },
  KeyH: {
    en: { key: 'h', keyUp: 'H' },
    ru: { key: 'р', keyUp: 'Р' },
    isFunc: false,
    width: '40px',
  },
  KeyJ: {
    en: { key: 'j', keyUp: 'J' },
    ru: { key: 'о', keyUp: 'О' },
    isFunc: false,
    width: '40px',
  },
  KeyK: {
    en: { key: 'k', keyUp: 'K' },
    ru: { key: 'л', keyUp: 'Л' },
    isFunc: false,
    width: '40px',
  },
  KeyL: {
    en: { key: 'l', keyUp: 'l' },
    ru: { key: 'д', keyUp: 'д' },
    isFunc: false,
    width: '40px',
  },
  Semicolon: {
    en: { key: ';', keyUp: ':' },
    ru: { key: 'ж', keyUp: 'Ж' },
    isFunc: false,
    width: '40px',
  },
  Quote: {
    en: { key: "'", keyUp: '"' },
    ru: { key: 'э', keyUp: 'Э' },
    isFunc: false,
    width: '40px',
  },
  Enter: {
    en: { key: 'Enter', keyUp: 'Enter' },
    ru: { key: 'Enter', keyUp: 'Enter' },
    isFunc: true,
    width: '90px',
  },
  ShiftLeft: {
    en: { key: 'Shift', keyUp: 'Shift' },
    ru: { key: 'Shift', keyUp: 'Shift' },
    isFunc: true,
    width: '90px',
  },
  KeyZ: {
    en: { key: 'z', keyUp: 'Z' },
    ru: { key: 'я', keyUp: 'Я' },
    isFunc: false,
    width: '40px',
  },
  KeyX: {
    en: { key: 'x', keyUp: 'X' },
    ru: { key: 'ч', keyUp: 'Ч' },
    isFunc: false,
    width: '40px',
  },
  KeyC: {
    en: { key: 'c', keyUp: 'C' },
    ru: { key: 'с', keyUp: 'С' },
    isFunc: false,
    width: '40px',
  },
  KeyV: {
    en: { key: 'v', keyUp: 'V' },
    ru: { key: 'м', keyUp: 'М' },
    isFunc: false,
    width: '40px',
  },
  KeyB: {
    en: { key: 'b', keyUp: 'B' },
    ru: { key: 'и', keyUp: 'И' },
    isFunc: false,
    width: '40px',
  },
  KeyN: {
    en: { key: 'n', keyUp: 'N' },
    ru: { key: 'т', keyUp: 'Т' },
    isFunc: false,
    width: '40px',
  },
  KeyM: {
    en: { key: 'm', keyUp: 'M' },
    ru: { key: 'ь', keyUp: 'Ь' },
    isFunc: false,
    width: '40px',
  },
  Comma: {
    en: { key: ',', keyUp: '<' },
    ru: { key: 'б', keyUp: 'Б' },
    isFunc: false,
    width: '40px',
  },
  Period: {
    en: { key: '.', keyUp: '>' },
    ru: { key: 'ю', keyUp: 'Ю' },
    isFunc: false,
    width: '40px',
  },
  Slash: {
    en: { key: '/', keyUp: '?' },
    ru: { key: '.', keyUp: ',' },
    isFunc: false,
    width: '40px',
  },
  ArrowUp: {
    en: { key: '▲', keyUp: '▲' },
    ru: { key: '▲', keyUp: '▲' },
    isFunc: false,
    width: '40px',
  },
  ShiftRight: {
    en: { key: 'Shift', keyUp: 'Shift' },
    ru: { key: 'Shift', keyUp: 'Shift' },
    isFunc: true,
    width: '90px',
  },
  ControlLeft: {
    en: { key: 'Control', keyUp: 'Control' },
    ru: { key: 'Control', keyUp: 'Control' },
    isFunc: true,
    width: '40px',
  },
  MetaLeft: {
    en: { key: 'Meta', keyUp: 'Meta' },
    ru: { key: 'Meta', keyUp: 'Meta' },
    isFunc: true,
    width: '40px',
  },
  AltLeft: {
    en: { key: 'Alt', keyUp: 'Alt' },
    ru: { key: 'Alt', keyUp: 'Alt' },
    isFunc: true,
    width: '40px',
  },
  Space: {
    en: { key: ' ', keyUp: ' ' },
    ru: { key: ' ', keyUp: ' ' },
    isFunc: false,
    width: '322px',
  },
  AltRight: {
    en: { key: 'Alt', keyUp: 'Alt' },
    ru: { key: 'Alt', keyUp: 'Alt' },
    isFunc: true,
    width: '40px',
  },
  ArrowLeft: {
    en: { key: '◄', keyUp: '◄' },
    ru: { key: '◄', keyUp: '◄' },
    isFunc: false,
    width: '40px',
  },
  ArrowDown: {
    en: { key: '▼', keyUp: '▼' },
    ru: { key: '▼', keyUp: '▼' },
    isFunc: false,
    width: '40px',
  },
  ArrowRight: {
    en: { key: '►', keyUp: '►' },
    ru: { key: '►', keyUp: '►' },
    isFunc: false,
    width: '40px',
  },
  ControlRight: {
    en: { key: 'Control', keyUp: 'Control' },
    ru: { key: 'Control', keyUp: 'Control' },
    isFunc: true,
    width: '40px',
  },
};
