export default {
  Backquote: {
    en: { key: '`', keyUp: '`' },
    ru: { key: 'ё', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Digit1: {
    en: { key: '1', keyUp: '!' },
    ru: { key: '1', keyUp: '!' },
    isFunc: false,
    width: '40px',
  },
  Digit2: {
    en: { key: '2', keyUp: '@' },
    ru: { key: '2', keyUp: '"' },
    isFunc: false,
    width: '40px',
  },
  Digit3: {
    en: { key: '3', keyUp: '#' },
    ru: { key: '3', keyUp: '№' },
    isFunc: false,
    width: '40px',
  },
  Digit4: {
    en: { key: '4', keyUp: '$' },
    ru: { key: '4', keyUp: ';' },
    isFunc: false,
    width: '40px',
  },
  Digit5: {
    en: { key: '5', keyUp: '%' },
    ru: { key: '5', keyUp: '%' },
    isFunc: false,
    width: '40px',
  },
  Digit6: {
    en: { key: '6', keyUp: '^' },
    ru: { key: '6', keyUp: ':' },
    isFunc: false,
    width: '40px',
  },
  Digit7: {
    en: { key: '7', keyUp: '&' },
    ru: { key: '7', keyUp: '?' },
    isFunc: false,
    width: '40px',
  },
  Digit8: {
    en: { key: '8', keyUp: '*' },
    ru: { key: '8', keyUp: '*' },
    isFunc: false,
    width: '40px',
  },
  Digit9: {
    en: { key: '9', keyUp: '(' },
    ru: { key: '9', keyUp: '(' },
    isFunc: false,
    width: '40px',
  },
  Digit0: {
    en: { key: '0', keyUp: ')' },
    ru: { key: '0', keyUp: ')' },
    isFunc: false,
    width: '40px',
  },
  Minus: {
    en: { key: '-', keyUp: '_' },
    ru: { key: '-', keyUp: '_' },
    isFunc: false,
    width: '40px',
  },
  Equal: {
    en: { key: '=', keyUp: '+' },
    ru: { key: '=', keyUp: '+' },
    isFunc: false,
    width: '40px',
  },
  Backspace: {
    en: { key: 'Backspace', keyUp: 'Backspace' },
    ru: { key: 'Backspace', keyUp: 'Backspace' },
    isFunc: true,
    width: '100px',
  },
  Tab: {
    en: { key: 'TAB', keyUp: 'TAB' },
    ru: { key: 'TAB', keyUp: 'TAB' },
    isFunc: false,
    width: '43px',
  },
  KeyQ: {
    en: { key: 'q', keyUp: null },
    ru: { key: 'й', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyW: {
    en: { key: 'w', keyUp: null },
    ru: { key: 'ц', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyE: {
    en: { key: 'e', keyUp: null },
    ru: { key: 'у', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyR: {
    en: { key: 'r', keyUp: null },
    ru: { key: 'к', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyT: {
    en: { key: 't', keyUp: null },
    ru: { key: 'е', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyY: {
    en: { key: 'y', keyUp: null },
    ru: { key: 'н', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyU: {
    en: { key: 'u', keyUp: null },
    ru: { key: 'г', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyI: {
    en: { key: 'i', keyUp: null },
    ru: { key: 'ш', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyO: {
    en: { key: 'o', keyUp: null },
    ru: { key: 'щ', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyP: {
    en: { key: 'p', keyUp: null },
    ru: { key: 'з', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  BracketLeft: {
    en: { key: '[', keyUp: '{' },
    ru: { key: 'х', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  BracketRight: {
    en: { key: ']', keyUp: '}' },
    ru: { key: 'ъ', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Backslash: {
    en: { key: '\\', keyUp: '|' },
    ru: { key: '\\', keyUp: '/' },
    isFunc: false,
    width: '40px',
  },
  Delete: {
    en: { key: 'Del', keyUp: 'Del' },
    ru: { key: 'Del', keyUp: 'Del' },
    isFunc: true,
    width: '43px',
  },
  CapsLock: {
    en: { key: 'CapsLock', keyUp: 'CapsLock' },
    ru: { key: 'CapsLock', keyUp: 'CapsLock' },
    isFunc: true,
    width: '90px',
  },
  KeyA: {
    en: { key: 'a', keyUp: null },
    ru: { key: 'ф', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyS: {
    en: { key: 's', keyUp: null },
    ru: { key: 'ы', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyD: {
    en: { key: 'd', keyUp: null },
    ru: { key: 'в', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyF: {
    en: { key: 'f', keyUp: null },
    ru: { key: 'а', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyG: {
    en: { key: 'g', keyUp: null },
    ru: { key: 'п', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyH: {
    en: { key: 'h', keyUp: null },
    ru: { key: 'р', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyJ: {
    en: { key: 'j', keyUp: null },
    ru: { key: 'о', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyK: {
    en: { key: 'k', keyUp: null },
    ru: { key: 'л', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyL: {
    en: { key: 'l', keyUp: null },
    ru: { key: 'д', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Semicolon: {
    en: { key: ';', keyUp: ':' },
    ru: { key: 'ж', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Quote: {
    en: { key: "'", keyUp: '"' },
    ru: { key: 'э', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Enter: {
    en: { key: 'ENTER', keyUp: 'ENTER' },
    ru: { key: 'ENTER', keyUp: 'ENTER' },
    isFunc: false,
    width: '90px',
  },
  ShiftLeft: {
    en: { key: 'Shift', keyUp: 'Shift' },
    ru: { key: 'Shift', keyUp: 'Shift' },
    isFunc: true,
    width: '90px',
  },
  KeyZ: {
    en: { key: 'z', keyUp: null },
    ru: { key: 'я', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyX: {
    en: { key: 'x', keyUp: null },
    ru: { key: 'ч', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyC: {
    en: { key: 'c', keyUp: null },
    ru: { key: 'с', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyV: {
    en: { key: 'v', keyUp: null },
    ru: { key: 'м', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyB: {
    en: { key: 'b', keyUp: null },
    ru: { key: 'и', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyN: {
    en: { key: 'n', keyUp: null },
    ru: { key: 'т', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  KeyM: {
    en: { key: 'm', keyUp: null },
    ru: { key: 'ь', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Comma: {
    en: { key: ',', keyUp: '<' },
    ru: { key: 'б', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Period: {
    en: { key: '.', keyUp: '>' },
    ru: { key: 'ю', keyUp: null },
    isFunc: false,
    width: '40px',
  },
  Slash: {
    en: { key: '/', keyUp: '?' },
    ru: { key: '.', keyUp: ',' },
    isFunc: false,
    width: '40px',
  },
  ArrowUp: {
    en: { key: '▲', keyUp: '▲' },
    ru: { key: '▲', keyUp: '▲' },
    isFunc: false,
    width: '40px',
  },
  ShiftRight: {
    en: { key: 'Shift', keyUp: 'Shift' },
    ru: { key: 'Shift', keyUp: 'Shift' },
    isFunc: true,
    width: '90px',
  },
  ControlLeft: {
    en: { key: 'Ctrl', keyUp: 'Ctrl' },
    ru: { key: 'Ctrl', keyUp: 'Ctrl' },
    isFunc: true,
    width: '40px',
  },
  MetaLeft: {
    en: { key: 'Win', keyUp: 'Win' },
    ru: { key: 'Win', keyUp: 'Win' },
    isFunc: true,
    width: '40px',
  },
  AltLeft: {
    en: { key: 'Alt', keyUp: 'Alt' },
    ru: { key: 'Alt', keyUp: 'Alt' },
    isFunc: true,
    width: '40px',
  },
  Space: {
    en: { key: ' ', keyUp: ' ' },
    ru: { key: ' ', keyUp: ' ' },
    isFunc: false,
    width: '322px',
  },
  AltRight: {
    en: { key: 'Alt', keyUp: 'Alt' },
    ru: { key: 'Alt', keyUp: 'Alt' },
    isFunc: true,
    width: '40px',
  },
  ArrowLeft: {
    en: { key: '◄', keyUp: '◄' },
    ru: { key: '◄', keyUp: '◄' },
    isFunc: false,
    width: '40px',
  },
  ArrowDown: {
    en: { key: '▼', keyUp: '▼' },
    ru: { key: '▼', keyUp: '▼' },
    isFunc: false,
    width: '40px',
  },
  ArrowRight: {
    en: { key: '►', keyUp: '►' },
    ru: { key: '►', keyUp: '►' },
    isFunc: false,
    width: '40px',
  },
  ControlRight: {
    en: { key: 'Ctrl', keyUp: 'Ctrl' },
    ru: { key: 'Ctrl', keyUp: 'Ctrl' },
    isFunc: true,
    width: '40px',
  },
};
